// Alla gränssnittssträngar (beslut 18). Svenska nu, engelska senare. Inga strängar i komponenterna.
export const S = {
  appName: 'Flaskor',
  nav: { cellar: 'Källaren', wishlist: 'Önskelistan', bar: 'Barskåpet', add: 'Lägg till', account: 'Konto' },
  login: {
    lead: 'Håll koll på vinkällaren, önskelistan och barskåpet. Delas med de du bor med.',
    google: 'Fortsätt med Google',
    or: 'eller med e-post',
    email: 'E-post',
    password: 'Lösenord',
    signIn: 'Logga in',
    register: 'Skapa konto',
    toRegister: 'Nytt här? Skapa konto',
    toSignIn: 'Har du konto? Logga in',
    forgot: 'Glömt lösenordet?',
    resetSent: (email: string) => `Ett mejl för nytt lösenord är skickat till ${email}.`,
    needEmail: 'Skriv e-postadressen först.',
    verifyTitle: 'Bekräfta din e-post',
    verifyLead: (email: string) => `Vi har skickat en länk till ${email}. Klicka på den och kom sedan tillbaka hit.`,
    verifyDone: 'Jag har bekräftat',
    verifyResend: 'Skicka länken igen',
    verifySent: 'Länken är skickad igen.',
    verifyStill: 'Adressen är inte bekräftad än.',
    signOut: 'Logga ut',
    loading: 'Loggar in …',
  },
  guest: {
    tryIt: 'Prova utan konto',
    tryLead: 'Allt sparas bara i den här webbläsaren. Du kan skapa konto senare och ta med det du lagt in.',
    banner: 'Sparas bara i den här webbläsaren.',
    bannerCta: 'Skapa konto',
    bannerLead: 'så sparas allt och kan delas med de du bor med.',
    bannerClose: 'Dölj',
    saved: 'Sparat i den här webbläsaren. Skapa konto så försvinner det inte om du rensar webbläsaren eller byter telefon.',
    householdName: 'Utan konto',
    lockTitle: 'Kräver konto',
    lockCta: 'Logga in eller skapa konto',
    lockClose: 'Inte nu',
    locks: {
      scan: 'Fotot läses av en AI-tjänst med en gemensam kvot. Med konto kan vi hålla ett tak per person, så den räcker åt alla.',
      stock: 'Lagersaldot slås upp på flaskan i ditt konto, så vi vet vilken vara det gäller.',
      refresh: 'Pris, tillgänglighet och betyg uppdateras på servern varje natt för flaskor som sparats i ett konto.',
    },
    accountTitle: 'Du använder Flaskor utan konto',
    accountLead: 'Det du lägger in sparas bara i den här webbläsaren. Rensar du webbläsaren, byter telefon eller dator, är det borta.',
    localWorks: 'Fungerar utan konto',
    localWorksList: ['Källaren, Önskelistan och Barskåpet', 'Lägga till via artikelnummer, länk eller namn', 'Skriva in själv och importera listor', 'Anteckningar om vad du druckit', 'Exportera som JSON eller CSV'],
    needsAccount: 'Kräver konto',
    needsAccountList: ['Spara på servern och se samma lista på alla enheter', 'Dela med de du bor med', 'Fota flaskan eller streckkoden', 'Lagersaldo i din butik', 'Pris och betyg som uppdateras varje natt'],
    create: 'Logga in eller skapa konto',
    carryOver: (n: number) => (n === 1 ? 'Flaskan du lagt in följer med till kontot.' : `De ${n} flaskorna du lagt in följer med till kontot.`),
    clear: 'Rensa lokal data',
    clearLead: 'Tar bort allt som sparats i den här webbläsaren. Går inte att ångra.',
    clearConfirm: 'Säkert? Tryck igen',
    pendingTitle: (n: number) => (n === 1 ? '1 flaska sparad lokalt' : `${n} flaskor sparade lokalt`),
    pendingLead: 'Du lade in dem innan du loggade in, och kontot hade redan flaskor. Vill du lägga till dem i kontot?',
    pendingUpload: 'Lägg till i kontot',
    pendingDiscard: 'Släng dem',
    pendingDone: (n: number) => (n === 1 ? '1 flaska tillagd i kontot.' : `${n} flaskor tillagda i kontot.`),
  },
  exportData: {
    title: 'Exportera data',
    lead: 'Hela listan som fil. JSON tar med allt, även anteckningarna. CSV öppnas i Excel, en rad per flaska.',
    json: 'Ladda ner JSON',
    csv: 'Ladda ner CSV',
    failed: 'Exporten misslyckades. Försök igen.',
  },
  account: {
    title: 'Konto',
    signedInAs: 'Inloggad som',
    household: 'Hushåll',
    householdLead: 'Alla i hushållet ser och ändrar samma källare, önskelista och barskåp.',
    rename: 'Spara namnet',
    members: 'Medlemmar',
    invite: 'Bjud in',
    inviteLead: 'Ge koden till den du vill dela med. Hen skapar ett konto och skriver in koden under Gå med i ett hushåll.',
    copy: 'Kopiera koden',
    copied: 'Kopierad',
    join: 'Gå med i ett hushåll',
    joinLead: 'Har du fått en kod? Då flyttar ditt konto dit. Det går bara när ditt eget hushåll är tomt.',
    joinPlaceholder: 'Kod',
    joinSubmit: 'Gå med',
    joinDone: 'Klart, du är med i hushållet.',
    joinNotFound: 'Ingen hushåll har den koden.',
    joinNotEmpty: 'Ditt hushåll har flaskor. Ta bort dem först, eller be den andra att gå med hos dig.',
    joinTooMany: 'För många försök. Vänta en minut.',
    signOut: 'Logga ut',
    delete: 'Radera kontot',
    deleteLead: 'Tar bort ditt konto. Är du ensam i hushållet raderas också alla flaskor och anteckningar. Går inte att ångra.',
    deleteConfirm: 'Säkert? Tryck igen',
    privacy: 'Integritet',
    gateMode: 'Appen är upplåst med grindkoden. Konton kommer när inloggningen är påslagen.',
  },
  privacy: [
    'Flaskor sparar din e-postadress och det du lägger in: flaskor, önskelista, barskåp och anteckningar. Inget annat, och ingen reklam eller spårning.',
    'Inloggningen sköts av Google Firebase. Dina flaskor ligger i en databas hos Cloudflare i Europa, och Cloudflare sparar tekniska loggar i några dagar.',
    'När du söker eller lägger till skickas namnet eller artikelnumret till Systembolaget, Vivino eller Caviste för att hämta pris och bakgrund. En streckkod slås upp hos Open Food Facts.',
    'Ett foto av en etikett skickas till Googles AI-tjänst Gemini för att läsas och sparas inte hos Flaskor. Enligt Googles villkor för Europa används det inte för att träna eller förbättra deras produkter, men Google kan spara det en begränsad tid för att upptäcka missbruk. Fota inget annat än flaskan.',
    'Webbläsaren sparar senaste listan och dina vyval, så appen fungerar utan nät.',
    'Radera kontot under Konto, så försvinner allt ovan hos Flaskor.',
    'Utan konto sparas det du lägger in bara i webbläsaren och skickas ingenstans, utom uppslagen ovan.',
  ],
  gate: {
    title: 'Grindkod',
    lead: 'Koden som låser upp hushållets flaskor. Sparas i den här webbläsaren.',
    placeholder: 'Kod',
    submit: 'Lås upp',
    wrong: 'Fel kod.',
    offline: 'Ingen kontakt med servern. Försök igen.',
  },
  pill: { wait: 'Vänta', drink: 'Drick', soon: 'Snart', past: 'Förbi', unknown: 'Okänt' },
  pillUnknownLong: 'Okänt · ange fönster',
  cellar: {
    title: 'Källaren',
    dueLabel: 'Dags att dricka:',
    search: 'Sök vin, öl, producent, druva',
    searchShort: 'Sök',
    all: 'Alla',
    drinkNow: 'Drick nu',
    show: 'Visa',
    sort: { price: 'Pris', vintage: 'Årgång', windowEnd: 'Fönsterslut', count: 'Antal', name: 'Namn', vivino: 'Betyg', lastDrunk: 'Senast drucken' },
    sortLabel: 'Sortera',
    sortDir: { asc: 'Stigande', desc: 'Fallande' },
    view: { list: 'Lista', table: 'Tabell' },
    columns: 'Kolumner',
    showZeroOn: 'Visar slut',
    showZeroOff: (n: number) => (n === 0 ? 'Visa slut' : `Visa slut (${n})`),
    empty: 'Inget i källaren än. Lägg till en flaska via Systembolagets artikelnummer.',
    noMatch: 'Inget matchar.',
    depleted: 'Slut',
    wines: (n: number) => (n === 1 ? '1 vara' : `${n} varor`),
    winesZero: (n: number) => (n === 1 ? '1 vara med noll flaskor' : `${n} varor med noll flaskor`),
    drankOne: 'Drack en',
    boughtMore: 'Köpte fler',
    rewish: 'Lägg på önskelistan igen',
  },
  wishlist: {
    title: 'Önskelistan',
    items: (n: number) => (n === 1 ? '1 vara' : `${n} varor`),
    all: 'Alla',
    wine: 'Vin',
    spirit: 'Sprit',
    beer: 'Öl',
    bought: 'Köpt',
    search: 'Sök vin, sprit, öl, producent',
    show: 'Visa',
    sort: { price: 'Pris', name: 'Namn', vivino: 'Betyg' },
    sortLabel: 'Sortera',
    noMatch: 'Inget matchar.',
    empty: 'Tomt. Lägg till något du vill köpa.',
    // Raden är "sortiment · status". Statusen gäller Systembolaget som helhet, butiken står på egen rad efter Kolla lagret.
    assortment: { BS: 'Ordervara', FS: 'Fast sortiment', FSB: 'Fast sortiment', FSN: 'Fast sortiment', FSÖ: 'Webblansering', TSE: 'Tillfälligt sortiment', TSV: 'Tillfälligt sortiment', TST: 'Tillfälligt sortiment', TSLS: 'Lokalt & småskaligt', TSS: 'Säsong' } as Record<string, string>,
    availability: {
      in_stock: 'Finns hos Systembolaget',
      orderable: 'Går att beställa',
      temporarily_out: 'Tillfälligt slut på centrallagret',
      supplier_out: 'Slut hos leverantören',
      sold_out: 'Slutsåld',
      discontinued: 'Utgått ur sortimentet',
      unknown: 'Caviste',
    },
    number: 'nr',
    sheet: {
      title: 'Köpt',
      toCellar: 'Flyttas till Källaren',
      toBar: 'Flyttas till Barskåpet',
      count: 'Antal',
      price: 'Pris per flaska',
      cancel: 'Avbryt',
      confirmCellar: 'Lägg i Källaren',
      confirmBar: 'Lägg i Barskåpet',
    },
  },
  bar: {
    title: 'Barskåpet',
    kinds: (n: number) => (n === 1 ? '1 sort' : `${n} sorter`),
    kindsZero: (n: number) => (n === 1 ? '1 sort med noll flaskor' : `${n} sorter med noll flaskor`),
    unopened: (n: number) => (n === 1 ? '1 oöppnad' : `${n} oöppnade`),
    noneOpen: 'ingen öppnad',
    openOne: 'Öppna en',
    openBottle: 'Öppnad flaska',
    level: { 4: 'Full', 3: 'Trekvart', 2: 'Halv', 1: 'Kvart' },
    empty: 'Inget i barskåpet.',
    depleted: 'Slut',
    search: 'Sök sprit, producent',
    all: 'Alla',
    show: 'Visa',
    sort: { name: 'Namn', category: 'Sort', count: 'Antal', price: 'Pris', open_level: 'Öppnad', lastDrunk: 'Senast drucken' },
    sortLabel: 'Sortera',
    noMatch: 'Inget matchar.',
  },
  add: {
    title: 'Lägg till',
    placeholder: 'Namn, artikelnummer, streckkod eller länk',
    hint: 'Skriv namnet på flaskan, eller klistra in artikelnummer, streckkodens siffror, eller en länk från Systembolaget, Caviste eller Vivino.',
    manual: 'Skriv in själv',
    manualTitle: 'Ny flaska',
    manualKind: { wine: 'Vin', spirit: 'Sprit', beer: 'Öl' },
    manualNext: 'Vidare',
    fromVivino: 'Hämtat från Vivino. Pris och drickfönster fyller du i själv.',
    fetched: (date: string) => `Hämtat ${date}.`,
    fetch: 'Hämta',
    fetching: 'Hämtar …',
    notFound: 'Hittade ingen vara med det numret.',
    badInput: 'Det där är varken ett artikelnummer, en streckkod eller en produktlänk.',
    failed: 'Systembolaget svarade inte. Försök igen.',
    window: 'Drickfönster · förifyllt',
    windowManual: 'Drickfönster',
    change: 'Ändra',
    done: 'Klar',
    from: 'Från',
    to: 'Till',
    taste: (source: string) => (source === 'caviste' ? 'Smak enligt Caviste' : 'Smak enligt Systembolaget'),
    toWishlist: 'Lägg på önskelistan',
    toCellar: 'Direkt till källaren',
    toBar: 'Direkt till barskåpet',
    saving: 'Sparar …',
  },
  scan: {
    button: 'Fota flaskan',
    hint: 'Etiketten eller streckkoden räcker. Streckkodens siffror går också att skriva i rutan ovan.',
    scanning: 'Läser flaskan …',
    read: (what: string) => `Läst från fotot: ${what}.`,
    readBarcode: (ean: string, what: string) => `Streckkod ${ean}: ${what}.`,
    pick: 'Vilken är det?',
    none: 'Ingen av dessa, skriv in själv',
    noHit: 'Ingen träff hos Systembolaget. Fyll i det som saknas.',
    unknownEan: 'Okänd streckkod. Fota etiketten i stället.',
    noBottle: 'Ingen flaska i bilden. Försök igen.',
    failed: 'Kunde inte läsa fotot. Försök igen, gärna med bättre ljus.',
    tooMany: 'Dagens fotokvot är slut. Skriv in flaskan själv, eller fota igen i morgon.',
  },
  detail: {
    serving: 'Servering',
    decant: 'Karaffering',
    decantNone: 'Ingen',
    decantHours: (h: number) => (h === 1 ? '1 timme' : `${h} timmar`),
    food: 'Mat',
    alcohol: 'Alkohol',
    taste: (source: string) => (source === 'caviste' ? 'Smak enligt Caviste' : 'Smak enligt Systembolaget'),
    note: 'Egen kommentar',
    countAtHome: 'Antal hemma',
    drankOne: 'Drack en',
    boughtMore: 'Köpte fler',
    pricePaid: 'Inköpspris',
    priceCurrent: 'Dagens pris',
    bought: 'Köpt',
    number: 'Artikelnummer',
    checked: 'Kollat',
    refresh: 'Uppdatera från Systembolaget',
    refreshing: 'Uppdaterar …',
    systembolaget: 'Visa på Systembolaget',
    caviste: 'Visa på Caviste',
    vivino: 'Sök på Vivino',
    distiller: 'Sök på Distiller',
    vivinoRated: (rating: string, votes: number | null) => (votes === null ? `★ ${rating} på Vivino` : `★ ${rating} på Vivino (${votes} röster)`),
    ownRated: (rating: string) => `★ ${rating}, visa betyget`,
    refreshVivino: 'Uppdatera Vivino-betyg',
    edit: 'Ändra',
    save: 'Spara',
    cancel: 'Avbryt',
    remove: 'Ta bort flaskan',
    removeConfirm: 'Säkert? Tryck igen för att ta bort',
    yearOf: (n: number, total: number) => `År ${n} av ${total}`,
    today: 'idag',
    notFound: 'Flaskan finns inte.',
    fields: {
      name: 'Namn',
      producer: 'Producent',
      vintage: 'Årgång',
      country: 'Land',
      region: 'Region',
      category: 'Kategori',
      grapes: 'Druvor',
      alcohol: 'Alkohol, %',
      volume: 'Volym, ml',
      drink_from: 'Drick från',
      drink_to: 'Drick till',
      serve_temp: 'Servering, °C',
      decant_hours: 'Karaffering, timmar',
      food: 'Mat',
      price_paid: 'Inköpspris, kr',
      note: 'Egen kommentar',
      taste: 'Smak',
      rating: 'Eget betyg, 1-5',
      rating_url: 'Länk till betyget',
      vivino_url: 'Vivino-länk',
      image_url: 'Bildlänk',
    },
  },
  tasting: {
    label: 'Drucket',
    add: 'Anteckna',
    date: 'När',
    rating: 'Betyg, 1 till 5',
    note: 'Vad tyckte ni?',
    remove: 'Ta bort anteckningen',
    empty: 'Inget antecknat än.',
    drunkOn: (date: string) => `Drucken ${date}`,
    times: (n: number) => (n === 1 ? '' : ` · ${n} ggr`),
    failed: 'Anteckningen gick inte att spara.',
  },
  caviste: {
    pick: 'Vilket vin i lådan?',
    lead: (n: number) => (n === 1 ? 'Lådan innehåller ett vin.' : `Lådan innehåller ${n} viner. Lägg till ett i taget.`),
    bottles: (n: number) => (n === 1 ? '1 flaska' : `${n} flaskor`),
  },
  stock: {
    label: 'Lager i butik',
    pick: 'Välj butik',
    search: 'Sök butik eller ort',
    change: 'Byt butik',
    loading: 'Kollar lagret …',
    check: 'Kolla lagret',
    checkAll: (n: number) => (n === 1 ? 'Kolla lagret för varan' : `Kolla lagret för alla ${n}`),
    summary: (found: number, of: number) => (found === 0 ? `Inget av de ${of} finns i butiken just nu.` : `${found} av ${of} finns i butiken.`),
    /** "48 st, hylla 14-04-03" */
    count: (n: number, shelf: string | null) => (shelf ? `${n} st, hylla ${shelf}` : `${n} st`),
    empty: 'Slut i butiken',
    notCarried: 'Förs inte i butiken',
    failed: 'Lagret gick inte att hämta.',
    hint: 'Saldot kommer från Systembolaget och kan ligga någon timme efter.',
  },
  search: {
    searching: 'Söker hos Systembolaget …',
    hits: (n: number) => (n === 1 ? '1 träff' : `${n} träffar`),
    none: 'Inga träffar hos Systembolaget. Prova färre ord, eller skriv in flaskan själv.',
  },
  import: {
    title: 'Importera lista',
    link: 'Importera en hel lista via din AI',
    lead: 'Kopiera prompten, klistra in den i din AI tillsammans med texten från Systembolagets lista (markera allt på sidan, kopiera), och klistra in svaret här.',
    copyPrompt: 'Kopiera prompten',
    copied: 'Kopierad',
    pasteLabel: 'AI:ns svar',
    pastePlaceholder: 'Klistra in JSON-svaret här',
    load: 'Läs in',
    badJson: 'Hittade ingen JSON-lista i texten. Be AI:n svara med bara listan.',
    empty: 'Listan är tom.',
    review: (n: number) => (n === 1 ? '1 vara att importera' : `${n} varor att importera`),
    allTo: 'Alla till',
    to: 'Till',
    dest: { wishlist: 'Önskelistan', cellar: 'Källaren', bar: 'Barskåpet' },
    status: { pending: 'Hämtar …', found: 'Systembolaget', notfound: 'Hittades inte, sparas som egen', manual: 'Egen' },
    count: 'Antal',
    include: 'Med',
    back: 'Börja om',
    import: (n: number) => `Importera ${n}`,
    importing: (i: number, n: number) => `Sparar ${i} av ${n} …`,
    done: (n: number) => (n === 1 ? 'Importerade 1 vara' : `Importerade ${n} varor`),
    prompt: `Du får text kopierad från Systembolagets webbplats (en sparad lista, en varukorg eller en sökning) eller annan text om vin och sprit. Plocka ut varje vara och svara ENBART med en JSON-lista, ett objekt per vara med exakt dessa fält:

- "nr": Systembolagets artikelnummer som sträng, bara siffror (4 till 7 siffror, "75624 01" skrivs "7562401"), eller null om det saknas
- "namn": varans namn, inklusive producent om den står med
- "argang": årgång som heltal, eller null
- "pris": pris i kronor som tal, eller null
- "antal": antal flaskor som heltal, 1 om inget står
- "typ": "vin" eller "sprit"

Ingen förklaring, ingen text före eller efter listan, inga kodstaket. Här är texten:

`,
  },
  undo: { undo: 'Ångra', close: 'Stäng', removed: (n: number) => (n === 1 ? 'Tog bort 1 flaska' : `Tog bort ${n} flaskor`), rewished: (n: number) => (n === 1 ? 'Flyttade 1 till önskelistan' : `Flyttade ${n} till önskelistan`) },
  bulk: { selected: (n: number) => (n === 1 ? '1 markerad' : `${n} markerade`), remove: 'Ta bort', rewish: 'Lägg på önskelistan igen', clear: 'Avmarkera', all: 'Markera alla' },
  rating: { votes: (n: number) => `Vivino, ${n} röster`, none: 'Inget betyg', own: 'Eget betyg' },
  units: { kr: 'kr', bottle: 'flaska', bottles: 'flaskor', bottleShort: 'fl', cl: 'cl' },
  bottles: (n: number) => (n === 1 ? '1 flaska' : `${n} flaskor`),
  bottlesShort: (n: number) => `${n} fl`,
  categoryShort: { 'Rött vin': 'Rött', 'Vitt vin': 'Vitt', 'Mousserande vin': 'Bubbel', 'Rosévin': 'Rosé' } as Record<string, string>,
  column: {
    name: 'Namn',
    vintage: 'Årgång',
    category: 'Typ',
    country: 'Land',
    region: 'Region',
    grapes: 'Druvor',
    count: 'Antal',
    price: 'Pris',
    total: 'Totalt',
    windowEnd: 'Drickes',
    serve_temp: 'Temp',
    decant: 'Karaff',
    food: 'Mat',
    vivino: 'Betyg',
    note: 'Kommentar',
    source: 'Källa',
    open_level: 'Öppnad',
    lastDrunk: 'Drucken',
  },
  error: { generic: 'Något gick fel.', offline: 'Ingen kontakt med servern.' },
  loading: 'Laddar …',
} as const
