// Alla gränssnittssträngar (beslut 18). Svenska nu, engelska senare. Inga strängar i komponenterna.
export const S = {
  appName: 'Flaskor',
  household: 'Patrik & Julia',
  nav: { cellar: 'Källaren', wishlist: 'Önskelistan', bar: 'Barskåpet', add: 'Lägg till' },
  gate: {
    title: 'Grindkod',
    lead: 'Koden som låser upp hushållets flaskor. Sparas i den här webbläsaren.',
    placeholder: 'Kod',
    submit: 'Lås upp',
    wrong: 'Fel kod.',
    offline: 'Ingen kontakt med servern. Försök igen.',
  },
  pill: { wait: 'Vänta', drink: 'Drick', soon: 'Snart', past: 'Förbi', unknown: 'Okänt' },
  pillUnknownLong: 'Okänt · ange fönster',
  cellar: {
    title: 'Källaren',
    dueLabel: 'Dags att dricka:',
    search: 'Sök vin, producent, druva',
    searchShort: 'Sök',
    all: 'Alla',
    drinkNow: 'Drick nu',
    show: 'Visa',
    sort: { price: 'Pris', vintage: 'Årgång', windowEnd: 'Fönsterslut', count: 'Antal', name: 'Namn', vivino: 'Vivino' },
    sortLabel: 'Sortera',
    sortDir: { asc: 'Stigande', desc: 'Fallande' },
    view: { list: 'Lista', table: 'Tabell' },
    columns: 'Kolumner',
    empty: 'Inga viner än. Lägg till ett via Systembolagets artikelnummer.',
    noMatch: 'Inget matchar.',
    depleted: 'Slut',
    wines: (n: number) => (n === 1 ? '1 vin' : `${n} viner`),
    winesZero: (n: number) => (n === 1 ? '1 vin med noll flaskor' : `${n} viner med noll flaskor`),
    drankOne: 'Drack en',
    boughtMore: 'Köpte fler',
    rewish: 'Lägg på önskelistan igen',
  },
  wishlist: {
    title: 'Önskelistan',
    items: (n: number) => (n === 1 ? '1 vara' : `${n} varor`),
    all: 'Alla',
    wine: 'Vin',
    spirit: 'Sprit',
    bought: 'Köpt',
    empty: 'Tomt. Lägg till något du vill köpa.',
    availability: {
      in_stock: 'Finns på Systembolaget',
      temporarily_out: 'Tillfälligt slut på Systembolaget',
      discontinued: 'Utgått hos Systembolaget',
      unknown: 'Caviste',
    },
    number: 'nr',
    sheet: {
      title: 'Köpt',
      toCellar: 'Flyttas till Källaren',
      toBar: 'Flyttas till Barskåpet',
      count: 'Antal',
      price: 'Pris per flaska',
      cancel: 'Avbryt',
      confirmCellar: 'Lägg i Källaren',
      confirmBar: 'Lägg i Barskåpet',
    },
  },
  bar: {
    title: 'Barskåpet',
    kinds: (n: number) => (n === 1 ? '1 sort' : `${n} sorter`),
    unopened: (n: number) => (n === 1 ? '1 oöppnad' : `${n} oöppnade`),
    noneOpen: 'ingen öppnad',
    openOne: 'Öppna en',
    openBottle: 'Öppnad flaska',
    level: { 4: 'Full', 3: 'Trekvart', 2: 'Halv', 1: 'Kvart' },
    empty: 'Inget i barskåpet.',
    depleted: 'Slut',
  },
  add: {
    title: 'Lägg till',
    placeholder: 'Artikelnummer eller produktlänk',
    hint: 'Artikelnummer eller produktlänk från Systembolaget.',
    fetched: (date: string) => `Hämtat ${date}.`,
    fetch: 'Hämta',
    fetching: 'Hämtar …',
    notFound: 'Hittade ingen vara med det numret.',
    badInput: 'Det där är varken ett artikelnummer eller en produktlänk.',
    failed: 'Systembolaget svarade inte. Försök igen.',
    window: 'Drickfönster · förifyllt',
    windowManual: 'Drickfönster',
    change: 'Ändra',
    done: 'Klar',
    from: 'Från',
    to: 'Till',
    taste: 'Smak enligt Systembolaget',
    toWishlist: 'Lägg på önskelistan',
    toCellar: 'Direkt till källaren',
    toBar: 'Direkt till barskåpet',
    saving: 'Sparar …',
  },
  detail: {
    serving: 'Servering',
    decant: 'Karaffering',
    decantNone: 'Ingen',
    decantHours: (h: number) => (h === 1 ? '1 timme' : `${h} timmar`),
    food: 'Mat',
    alcohol: 'Alkohol',
    taste: 'Smak enligt Systembolaget',
    note: 'Egen kommentar',
    countAtHome: 'Antal hemma',
    drankOne: 'Drack en',
    boughtMore: 'Köpte fler',
    pricePaid: 'Inköpspris',
    priceCurrent: 'Dagens pris',
    bought: 'Köpt',
    number: 'Artikelnummer',
    checked: 'Kollat',
    refresh: 'Uppdatera från Systembolaget',
    refreshing: 'Uppdaterar …',
    systembolaget: 'Visa på Systembolaget',
    caviste: 'Visa på Caviste',
    vivino: 'Betyg på Vivino',
    edit: 'Ändra',
    save: 'Spara',
    cancel: 'Avbryt',
    yearOf: (n: number, total: number) => `År ${n} av ${total}`,
    today: 'idag',
    notFound: 'Flaskan finns inte.',
    fields: {
      name: 'Namn',
      producer: 'Producent',
      vintage: 'Årgång',
      country: 'Land',
      region: 'Region',
      category: 'Kategori',
      grapes: 'Druvor',
      alcohol: 'Alkohol, %',
      volume: 'Volym, ml',
      drink_from: 'Drick från',
      drink_to: 'Drick till',
      serve_temp: 'Servering, °C',
      decant_hours: 'Karaffering, timmar',
      food: 'Mat',
      price_paid: 'Inköpspris, kr',
      note: 'Egen kommentar',
      taste: 'Smak',
    },
  },
  rating: { votes: (n: number) => `Vivino, ${n} röster`, none: 'Inget betyg' },
  units: { kr: 'kr', bottle: 'flaska', bottles: 'flaskor', bottleShort: 'fl', cl: 'cl' },
  bottles: (n: number) => (n === 1 ? '1 flaska' : `${n} flaskor`),
  bottlesShort: (n: number) => `${n} fl`,
  categoryShort: { 'Rött vin': 'Rött', 'Vitt vin': 'Vitt', 'Mousserande vin': 'Bubbel', 'Rosévin': 'Rosé' } as Record<string, string>,
  column: {
    name: 'Namn',
    vintage: 'Årgång',
    category: 'Typ',
    country: 'Land',
    region: 'Region',
    grapes: 'Druvor',
    count: 'Antal',
    price: 'Pris',
    total: 'Totalt',
    windowEnd: 'Drickes',
    serve_temp: 'Temp',
    decant: 'Karaff',
    food: 'Mat',
    vivino: 'Vivino',
  },
  error: { generic: 'Något gick fel.', offline: 'Ingen kontakt med servern.' },
  loading: 'Laddar …',
} as const
