// Alla gränssnittssträngar (beslut 18). Svenska nu, engelska senare. Inga strängar i komponenterna.
export const S = {
  appName: 'Flaskor',
  household: 'Patrik & Julia',
  nav: { cellar: 'Källaren', wishlist: 'Önskelistan', bar: 'Barskåpet', add: 'Lägg till' },
  gate: {
    title: 'Grindkod',
    lead: 'Koden som låser upp hushållets flaskor. Sparas i den här webbläsaren.',
    placeholder: 'Kod',
    submit: 'Lås upp',
    wrong: 'Fel kod.',
    offline: 'Ingen kontakt med servern. Försök igen.',
  },
  pill: { wait: 'Vänta', drink: 'Drick', soon: 'Snart', past: 'Förbi', unknown: 'Okänt' },
  pillUnknownLong: 'Okänt · ange fönster',
  cellar: {
    title: 'Källaren',
    dueLabel: 'Dags att dricka:',
    search: 'Sök vin, öl, producent, druva',
    searchShort: 'Sök',
    all: 'Alla',
    drinkNow: 'Drick nu',
    show: 'Visa',
    sort: { price: 'Pris', vintage: 'Årgång', windowEnd: 'Fönsterslut', count: 'Antal', name: 'Namn', vivino: 'Betyg' },
    sortLabel: 'Sortera',
    sortDir: { asc: 'Stigande', desc: 'Fallande' },
    view: { list: 'Lista', table: 'Tabell' },
    columns: 'Kolumner',
    showZeroOn: 'Visar slut',
    showZeroOff: (n: number) => (n === 0 ? 'Visa slut' : `Visa slut (${n})`),
    empty: 'Inget i källaren än. Lägg till en flaska via Systembolagets artikelnummer.',
    noMatch: 'Inget matchar.',
    depleted: 'Slut',
    wines: (n: number) => (n === 1 ? '1 vara' : `${n} varor`),
    winesZero: (n: number) => (n === 1 ? '1 vara med noll flaskor' : `${n} varor med noll flaskor`),
    drankOne: 'Drack en',
    boughtMore: 'Köpte fler',
    rewish: 'Lägg på önskelistan igen',
  },
  wishlist: {
    title: 'Önskelistan',
    items: (n: number) => (n === 1 ? '1 vara' : `${n} varor`),
    all: 'Alla',
    wine: 'Vin',
    spirit: 'Sprit',
    beer: 'Öl',
    bought: 'Köpt',
    search: 'Sök vin, sprit, öl, producent',
    show: 'Visa',
    sort: { price: 'Pris', name: 'Namn', vivino: 'Betyg' },
    sortLabel: 'Sortera',
    noMatch: 'Inget matchar.',
    empty: 'Tomt. Lägg till något du vill köpa.',
    availability: {
      in_stock: 'Finns på Systembolaget',
      temporarily_out: 'Tillfälligt slut på Systembolaget',
      discontinued: 'Utgått hos Systembolaget',
      unknown: 'Caviste',
    },
    number: 'nr',
    sheet: {
      title: 'Köpt',
      toCellar: 'Flyttas till Källaren',
      toBar: 'Flyttas till Barskåpet',
      count: 'Antal',
      price: 'Pris per flaska',
      cancel: 'Avbryt',
      confirmCellar: 'Lägg i Källaren',
      confirmBar: 'Lägg i Barskåpet',
    },
  },
  bar: {
    title: 'Barskåpet',
    kinds: (n: number) => (n === 1 ? '1 sort' : `${n} sorter`),
    kindsZero: (n: number) => (n === 1 ? '1 sort med noll flaskor' : `${n} sorter med noll flaskor`),
    unopened: (n: number) => (n === 1 ? '1 oöppnad' : `${n} oöppnade`),
    noneOpen: 'ingen öppnad',
    openOne: 'Öppna en',
    openBottle: 'Öppnad flaska',
    level: { 4: 'Full', 3: 'Trekvart', 2: 'Halv', 1: 'Kvart' },
    empty: 'Inget i barskåpet.',
    depleted: 'Slut',
    search: 'Sök sprit, producent',
    all: 'Alla',
    show: 'Visa',
    sort: { name: 'Namn', category: 'Sort', count: 'Antal', price: 'Pris', open_level: 'Öppnad' },
    sortLabel: 'Sortera',
    noMatch: 'Inget matchar.',
  },
  add: {
    title: 'Lägg till',
    placeholder: 'Namn, artikelnummer, streckkod eller länk',
    hint: 'Skriv namnet på flaskan, eller klistra in artikelnummer, streckkodens siffror, eller en länk från Systembolaget, Caviste eller Vivino.',
    manual: 'Skriv in själv',
    manualTitle: 'Ny flaska',
    manualKind: { wine: 'Vin', spirit: 'Sprit', beer: 'Öl' },
    manualNext: 'Vidare',
    fromVivino: 'Hämtat från Vivino. Pris och drickfönster fyller du i själv.',
    fetched: (date: string) => `Hämtat ${date}.`,
    fetch: 'Hämta',
    fetching: 'Hämtar …',
    notFound: 'Hittade ingen vara med det numret.',
    badInput: 'Det där är varken ett artikelnummer, en streckkod eller en produktlänk.',
    failed: 'Systembolaget svarade inte. Försök igen.',
    window: 'Drickfönster · förifyllt',
    windowManual: 'Drickfönster',
    change: 'Ändra',
    done: 'Klar',
    from: 'Från',
    to: 'Till',
    taste: (source: string) => (source === 'caviste' ? 'Smak enligt Caviste' : 'Smak enligt Systembolaget'),
    toWishlist: 'Lägg på önskelistan',
    toCellar: 'Direkt till källaren',
    toBar: 'Direkt till barskåpet',
    saving: 'Sparar …',
  },
  scan: {
    button: 'Fota flaskan',
    hint: 'Etiketten eller streckkoden räcker. Streckkodens siffror går också att skriva i rutan ovan.',
    scanning: 'Läser flaskan …',
    read: (what: string) => `Läst från fotot: ${what}.`,
    readBarcode: (ean: string, what: string) => `Streckkod ${ean}: ${what}.`,
    pick: 'Vilken är det?',
    none: 'Ingen av dessa, skriv in själv',
    noHit: 'Ingen träff hos Systembolaget. Fyll i det som saknas.',
    unknownEan: 'Okänd streckkod. Fota etiketten i stället.',
    noBottle: 'Ingen flaska i bilden. Försök igen.',
    failed: 'Kunde inte läsa fotot. Försök igen, gärna med bättre ljus.',
  },
  detail: {
    serving: 'Servering',
    decant: 'Karaffering',
    decantNone: 'Ingen',
    decantHours: (h: number) => (h === 1 ? '1 timme' : `${h} timmar`),
    food: 'Mat',
    alcohol: 'Alkohol',
    taste: (source: string) => (source === 'caviste' ? 'Smak enligt Caviste' : 'Smak enligt Systembolaget'),
    note: 'Egen kommentar',
    countAtHome: 'Antal hemma',
    drankOne: 'Drack en',
    boughtMore: 'Köpte fler',
    pricePaid: 'Inköpspris',
    priceCurrent: 'Dagens pris',
    bought: 'Köpt',
    number: 'Artikelnummer',
    checked: 'Kollat',
    refresh: 'Uppdatera från Systembolaget',
    refreshing: 'Uppdaterar …',
    systembolaget: 'Visa på Systembolaget',
    caviste: 'Visa på Caviste',
    vivino: 'Sök på Vivino',
    distiller: 'Sök på Distiller',
    vivinoRated: (rating: string, votes: number | null) => (votes === null ? `★ ${rating} på Vivino` : `★ ${rating} på Vivino (${votes} röster)`),
    ownRated: (rating: string) => `★ ${rating}, visa betyget`,
    refreshVivino: 'Uppdatera Vivino-betyg',
    edit: 'Ändra',
    save: 'Spara',
    cancel: 'Avbryt',
    remove: 'Ta bort flaskan',
    removeConfirm: 'Säkert? Tryck igen för att ta bort',
    yearOf: (n: number, total: number) => `År ${n} av ${total}`,
    today: 'idag',
    notFound: 'Flaskan finns inte.',
    fields: {
      name: 'Namn',
      producer: 'Producent',
      vintage: 'Årgång',
      country: 'Land',
      region: 'Region',
      category: 'Kategori',
      grapes: 'Druvor',
      alcohol: 'Alkohol, %',
      volume: 'Volym, ml',
      drink_from: 'Drick från',
      drink_to: 'Drick till',
      serve_temp: 'Servering, °C',
      decant_hours: 'Karaffering, timmar',
      food: 'Mat',
      price_paid: 'Inköpspris, kr',
      note: 'Egen kommentar',
      taste: 'Smak',
      rating: 'Eget betyg, 1-5',
      rating_url: 'Länk till betyget',
      vivino_url: 'Vivino-länk',
      image_url: 'Bildlänk',
    },
  },
  tasting: {
    label: 'Drucket',
    add: 'Anteckna',
    date: 'När',
    rating: 'Betyg, 1 till 5',
    note: 'Vad tyckte ni?',
    remove: 'Ta bort anteckningen',
    empty: 'Inget antecknat än.',
    failed: 'Anteckningen gick inte att spara.',
  },
  caviste: {
    pick: 'Vilket vin i lådan?',
    lead: (n: number) => (n === 1 ? 'Lådan innehåller ett vin.' : `Lådan innehåller ${n} viner. Lägg till ett i taget.`),
    bottles: (n: number) => (n === 1 ? '1 flaska' : `${n} flaskor`),
  },
  stock: {
    label: 'Lager i butik',
    pick: 'Välj butik',
    search: 'Sök butik eller ort',
    change: 'Byt butik',
    loading: 'Kollar lagret …',
    check: 'Kolla lagret',
    /** "48 st, hylla 14-04-03" */
    count: (n: number, shelf: string | null) => (shelf ? `${n} st, hylla ${shelf}` : `${n} st`),
    empty: 'Slut i butiken',
    notCarried: 'Förs inte i butiken',
    failed: 'Lagret gick inte att hämta.',
    hint: 'Saldot kommer från Systembolaget och kan ligga någon timme efter.',
  },
  search: {
    searching: 'Söker hos Systembolaget …',
    hits: (n: number) => (n === 1 ? '1 träff' : `${n} träffar`),
    none: 'Inga träffar hos Systembolaget. Prova färre ord, eller skriv in flaskan själv.',
  },
  import: {
    title: 'Importera lista',
    link: 'Importera en hel lista via din AI',
    lead: 'Kopiera prompten, klistra in den i din AI tillsammans med texten från Systembolagets lista (markera allt på sidan, kopiera), och klistra in svaret här.',
    copyPrompt: 'Kopiera prompten',
    copied: 'Kopierad',
    pasteLabel: 'AI:ns svar',
    pastePlaceholder: 'Klistra in JSON-svaret här',
    load: 'Läs in',
    badJson: 'Hittade ingen JSON-lista i texten. Be AI:n svara med bara listan.',
    empty: 'Listan är tom.',
    review: (n: number) => (n === 1 ? '1 vara att importera' : `${n} varor att importera`),
    allTo: 'Alla till',
    to: 'Till',
    dest: { wishlist: 'Önskelistan', cellar: 'Källaren', bar: 'Barskåpet' },
    status: { pending: 'Hämtar …', found: 'Systembolaget', notfound: 'Hittades inte, sparas som egen', manual: 'Egen' },
    count: 'Antal',
    include: 'Med',
    back: 'Börja om',
    import: (n: number) => `Importera ${n}`,
    importing: (i: number, n: number) => `Sparar ${i} av ${n} …`,
    done: (n: number) => (n === 1 ? 'Importerade 1 vara' : `Importerade ${n} varor`),
    prompt: `Du får text kopierad från Systembolagets webbplats (en sparad lista, en varukorg eller en sökning) eller annan text om vin och sprit. Plocka ut varje vara och svara ENBART med en JSON-lista, ett objekt per vara med exakt dessa fält:

- "nr": Systembolagets artikelnummer som sträng, bara siffror (4 till 7 siffror, "75624 01" skrivs "7562401"), eller null om det saknas
- "namn": varans namn, inklusive producent om den står med
- "argang": årgång som heltal, eller null
- "pris": pris i kronor som tal, eller null
- "antal": antal flaskor som heltal, 1 om inget står
- "typ": "vin" eller "sprit"

Ingen förklaring, ingen text före eller efter listan, inga kodstaket. Här är texten:

`,
  },
  undo: { undo: 'Ångra', close: 'Stäng', removed: (n: number) => (n === 1 ? 'Tog bort 1 flaska' : `Tog bort ${n} flaskor`), rewished: (n: number) => (n === 1 ? 'Flyttade 1 till önskelistan' : `Flyttade ${n} till önskelistan`) },
  bulk: { selected: (n: number) => (n === 1 ? '1 markerad' : `${n} markerade`), remove: 'Ta bort', rewish: 'Lägg på önskelistan igen', clear: 'Avmarkera', all: 'Markera alla' },
  rating: { votes: (n: number) => `Vivino, ${n} röster`, none: 'Inget betyg', own: 'Eget betyg' },
  units: { kr: 'kr', bottle: 'flaska', bottles: 'flaskor', bottleShort: 'fl', cl: 'cl' },
  bottles: (n: number) => (n === 1 ? '1 flaska' : `${n} flaskor`),
  bottlesShort: (n: number) => `${n} fl`,
  categoryShort: { 'Rött vin': 'Rött', 'Vitt vin': 'Vitt', 'Mousserande vin': 'Bubbel', 'Rosévin': 'Rosé' } as Record<string, string>,
  column: {
    name: 'Namn',
    vintage: 'Årgång',
    category: 'Typ',
    country: 'Land',
    region: 'Region',
    grapes: 'Druvor',
    count: 'Antal',
    price: 'Pris',
    total: 'Totalt',
    windowEnd: 'Drickes',
    serve_temp: 'Temp',
    decant: 'Karaff',
    food: 'Mat',
    vivino: 'Betyg',
    note: 'Kommentar',
    source: 'Källa',
    open_level: 'Öppnad',
  },
  error: { generic: 'Något gick fel.', offline: 'Ingen kontakt med servern.' },
  loading: 'Laddar …',
} as const
